services:
  store_db:
    container_name: 'store_db'
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5499:5432
    volumes:
      - store_db:/var/lib/postgresql/data

volumes:
  store_db:
